In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import Image

In [2]:
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.svm import LinearSVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV

In [3]:
pwd

'C:\\Users\\anafa\\OneDrive\\Desktop\\TOMI\\2020\\Ciencia de Datos\\DESCARGAS DE CLASES\\tarea clase 08'

In [4]:
xy_train=pd.read_csv(r'C:\\Users\\anafa\\OneDrive\\Desktop\\TOMI\\2020\\Ciencia de Datos\\DESCARGAS DE CLASES\\tarea clase 08\\Xy_train.csv', delimiter=',', parse_dates = True)

In [5]:
np.shape(xy_train)

(100, 2)

In [6]:
xy_train.head(10)

X          y
0  2.273360   6.054685
1  3.167583   4.581428
2  7.973655   5.392507
3  6.762547   3.108068
4  3.911096   4.225744
5  3.328139   5.404029
6  5.983088   3.804639
7  1.867342   5.753330
8  6.727560   4.649223
9  9.418029  11.237918

In [7]:
x_test=pd.read_csv(r'C:\\Users\\anafa\\OneDrive\\Desktop\\TOMI\\2020\\Ciencia de Datos\\DESCARGAS DE CLASES\\tarea clase 08\\X_test.csv', delimiter=',', parse_dates = True)

In [8]:
xtest=pd.DataFrame(x_test.X)
xtest

X
0   6.170800
1   6.302022
2   8.689293
3   2.376897
4   2.707320
5   6.555949
6   8.492565
7   0.111064
8   9.121449
9   2.675377
10  3.242831
11  6.416299
12  9.158768
13  0.659650
14  4.682379
15  8.109528
16  4.961968
17  6.013856
18  7.149417
19  6.279854

In [9]:
xtrain=pd.DataFrame(xy_train.X)
xtrain

X
0   2.273360
1   3.167583
2   7.973655
3   6.762547
4   3.911096
..       ...
95  3.787495
96  2.759471
97  9.661041
98  0.582026
99  4.087339

[100 rows x 1 columns]

In [10]:
ytrain=pd.DataFrame(xy_train.y)
ytrain

y
0    6.054685
1    4.581428
2    5.392507
3    3.108068
4    4.225744
..        ...
95   5.133706
96   4.308327
97  11.923565
98   1.335725
99   5.641851

[100 rows x 1 columns]

In [11]:
scaler = preprocessing.StandardScaler().fit(xtrain)
scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

In [12]:
xtrain_scal = scaler.transform(xtrain)
xtrain_scal

array([[-0.83113431],
       [-0.50247012],
       [ 1.26396082],
       [ 0.81882833],
       [-0.22919851],
       [-0.44345916],
       [ 0.53234469],
       [-0.98036293],
       [ 0.80596943],
       [ 1.79482833],
       [-0.75428249],
       [ 1.82084398],
       [ 0.78568631],
       [-1.31422391],
       [-0.04274425],
       [ 1.59149351],
       [ 0.89674284],
       [-0.4667652 ],
       [ 1.03080239],
       [-0.85760122],
       [-1.36679473],
       [-1.07900589],
       [-0.41667913],
       [ 0.04308952],
       [-0.68748066],
       [ 1.3316287 ],
       [-0.95625146],
       [-1.19083601],
       [-1.32978262],
       [ 0.53329758],
       [ 1.47484311],
       [ 0.54451946],
       [ 1.75875595],
       [ 0.99718409],
       [ 1.49619512],
       [ 1.74901404],
       [ 0.34077194],
       [ 1.77964921],
       [ 0.15259775],
       [-0.66045844],
       [-0.00621414],
       [ 0.7776058 ],
       [-0.45052697],
       [ 1.65388034],
       [-0.72183423],
       [-0

In [13]:
xtest_scal = scaler.transform(xtest) 
xtest_scal

array([[ 0.60133689],
       [ 0.64956642],
       [ 1.52698781],
       [-0.79308015],
       [-0.67163613],
       [ 0.74289499],
       [ 1.45468186],
       [-1.62586815],
       [ 1.68582281],
       [-0.68337629],
       [-0.47481344],
       [ 0.69156777],
       [ 1.69953909],
       [-1.42423996],
       [ 0.0542804 ],
       [ 1.31389992],
       [ 0.15704091],
       [ 0.54365321],
       [ 0.96101926],
       [ 0.64141879]])

In [19]:
#Uilizo SVR

In [15]:
est = SVR(max_iter=25000)
parameters_svr_rbf = {'kernel':['linear', 'rbf'] , 'C': [1,500,1000,2000,3000,4000],'gamma': [0.01,0.05,0.07,0.1]}
gs = GridSearchCV(est, param_grid=parameters_svr_rbf,refit=True,
                  cv=5, scoring="neg_mean_squared_error",
                  verbose=3, n_jobs=3)

In [16]:
# Fiteo
gs.fit(xtrain_scal, ytrain)

Fitting 5 folds for each of 48 candidates, totalling 240 fits


[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  28 tasks      | elapsed:    2.4s
[Parallel(n_jobs=3)]: Done 240 out of 240 | elapsed:    3.5s finished
C:\Users\anafa\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GridSearchCV(cv=5, error_score=nan,
             estimator=SVR(C=1.0, cache_size=200, coef0=0.0, degree=3,
                           epsilon=0.1, gamma='scale', kernel='rbf',
                           max_iter=25000, shrinking=True, tol=0.001,
                           verbose=False),
             iid='deprecated', n_jobs=3,
             param_grid={'C': [1, 500, 1000, 2000, 3000, 4000],
                         'gamma': [0.01, 0.05, 0.07, 0.1],
                         'kernel': ['linear', 'rbf']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='neg_mean_squared_error', verbose=3)

In [17]:
print(gs.best_estimator_, "\n")

SVR(C=3000, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma=0.05,
    kernel='rbf', max_iter=25000, shrinking=True, tol=0.001, verbose=False) 



In [18]:
svr_prediction = gs.best_estimator_.predict(xtest_scal)
svr_prediction

array([3.4180561 , 3.42605132, 7.63439031, 5.03920402, 5.15951183,
       3.49295218, 6.93990934, 0.09634606, 9.40447738, 5.15310488,
       5.12161002, 3.44743575, 9.57319326, 2.03720916, 4.17978935,
       5.78357075, 3.96129616, 3.43015378, 3.9533663 , 3.42348628])